Repository FC-DEV-FinalProject/FinalProject_team3_BE, pull requests merged in 2024-12, with the labels that each got.

#149 :bug: [bugHot] : security custom header 추가
  src/main/java/com/investmetic/domain/user/dto/request/UserSignUpDto.java
  src/main/java/com/investmetic/global/config/SecurityConfig.java
Labels: 🐛 fix

#147 리뷰,전략 api 버그수정 및 시큐리티 적용
  src/main/java/com/investmetic/domain/review/controller/ReviewController.java
  src/main/java/com/investmetic/domain/review/dto/response/ReviewDetailResponse.java
  src/main/java/com/investmetic/domain/review/repository/ReviewRepository.java
  src/main/java/com/investmetic/domain/review/service/ReviewService.java
  src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/investmetic/domain/strategy/controller/StrategyDetailController.java
  src/main/java/com/investmetic/domain/strategy/controller/StrategyRankingController.java
  src/main/java/com/investmetic/domain/strategy/dto/AnalysisDataDto.java
  src/main/java/com/investmetic/domain/strategy/repository/DailyAnalysisRepositoryCustom.java
  src/main/java/com/investmetic/domain/strategy/repository/DailyAnalysisRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepositoryCustom.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyDetailService.java
  src/main/java/com/investmetic/global/exception/ErrorCode.java
  src/test/java/com/investmetic/domain/TestEntity/TestEntityFactory.java
  src/test/java/com/investmetic/domain/review/service/ReviewServiceTest.java
  src/test/java/com/investmetic/domain/strategy/service/StrategyDetailServiceTest.java
Labels: ♻️ Refactor, 🧪 Test, 🐛 fix, ⚡️ Performance

#150 Refactor/trader create daily analysis #143
  src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyAnalysisService.java
  src/main/java/com/investmetic/domain/user/model/entity/User.java
  src/main/java/com/investmetic/global/config/SwaggerConfig.java
  src/test/java/com/investmetic/domain/strategy/service/StrategyDailyAnalysisServiceTest.java
Labels: ♻️ Refactor, 🐛 fix

#152 Refactor/trader modify daily analysis #151
  src/main/java/com/investmetic/domain/review/controller/ReviewController.java
  src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/investmetic/domain/strategy/controller/StrategyDetailController.java
  src/main/java/com/investmetic/domain/strategy/controller/StrategyRankingController.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyAnalysisService.java
  src/main/java/com/investmetic/domain/user/model/entity/User.java
  src/test/java/com/investmetic/domain/strategy/service/StrategyDailyAnalysisServiceTest.java
Labels: ♻️ Refactor, 🧪 Test, 🐛 fix

#131 Feat/전화번호를 통한 이메일 찾기 기능 구현 #124
  src/main/java/com/investmetic/domain/user/controller/LoginController.java
  src/main/java/com/investmetic/domain/user/controller/UserController.java
  src/main/java/com/investmetic/domain/user/dto/response/FoundEmailDto.java
  src/main/java/com/investmetic/domain/user/repository/UserRepository.java
  src/main/java/com/investmetic/domain/user/service/UserService.java
  src/main/java/com/investmetic/global/config/SecurityConfig.java
  src/test/java/com/investmetic/domain/user/service/UserServiceTest.java
Labels: ✨ Feature, 🐛 fix

#155 Refactor/strategy authorization #153
  src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/investmetic/domain/strategy/model/entity/DailyAnalysis.java
  src/main/java/com/investmetic/domain/strategy/model/entity/Strategy.java
  src/main/java/com/investmetic/domain/strategy/repository/TradeTypeRepository.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyService.java
  src/main/java/com/investmetic/global/scheduler/DailyAnalysisScheduler.java
  src/test/java/com/investmetic/domain/strategy/service/StrategyServiceTest.java
Labels: 🧪 Test, 🐛 fix

#159 🐛 [refactor] cookie "/" 추가
  src/main/java/com/investmetic/global/security/handler/CustomAuthenticationSuccessHandler.java
Labels: 🐛 fix

#157 Fix/strateies graph #154
  src/main/java/com/investmetic/domain/strategy/dto/ProfitRateChartDto.java
  src/main/java/com/investmetic/domain/strategy/dto/ProfitRateData.java
  src/main/java/com/investmetic/domain/strategy/dto/response/AdminStrategyResponseDto.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepositoryCustom.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyListingService.java
Labels: ♻️ Refactor, 🐛 fix

#164 🐛 [fix] cors 문제 해결
  src/main/java/com/investmetic/global/config/CorsProperties.java
  src/main/java/com/investmetic/global/config/SecurityConfig.java
Labels: 🐛 fix

#158 🐛 [fix] 전략 삭제 시 관련된 전략 부분 전체 삭제 로직 추가
  src/main/java/com/investmetic/domain/accountverification/repository/AccountVerificationRepository.java
  src/main/java/com/investmetic/domain/review/repository/ReviewRepository.java
  src/main/java/com/investmetic/domain/strategy/repository/MonthlyAnalysisRepository.java
  src/main/java/com/investmetic/domain/strategy/repository/StockTypeGroupRepository.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyService.java
  src/main/java/com/investmetic/domain/subscription/repository/SubscriptionRepositoryCustom.java
  src/main/java/com/investmetic/domain/subscription/repository/SubscriptionRepositoryCustomImpl.java
  src/main/java/com/investmetic/global/exception/ErrorCode.java
  src/main/java/com/investmetic/global/util/s3/FilePath.java
  src/main/java/com/investmetic/global/util/s3/S3FileService.java
  src/test/java/com/investmetic/domain/strategy/service/StrategyServiceTest.java
Labels: 🐛 fix

#170 리뷰목록조회 버그 해결 및 구독 리팩토링
  src/main/java/com/investmetic/domain/review/dto/response/ReviewDetailResponse.java
  src/main/java/com/investmetic/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/investmetic/domain/subscription/controller/SubscribeController.java
  src/main/java/com/investmetic/domain/subscription/service/SubscriptionService.java
  src/main/java/com/investmetic/global/exception/ErrorCode.java
  src/test/java/com/investmetic/domain/subscription/service/SubscribtionServiceTest.java
Labels: ✨ Feature, ♻️ Refactor, 🧪 Test, 🐛 fix, ⚡️ Performance

#175 🐛 [fix] 전략 분석그래프 데이터 오류 수정
  src/main/java/com/investmetic/domain/strategy/repository/DailyAnalysisRepositoryCustomImpl.java
Labels: 🚨Hotfix

#178 🐛 [fix] 전략 관련 유효성 검사 추가
  src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/investmetic/domain/strategy/dto/request/StrategyModifyRequestDto.java
  src/main/java/com/investmetic/domain/strategy/dto/request/StrategyRegisterRequestDto.java
  src/main/java/com/investmetic/domain/strategy/dto/request/TraderDailyAnalysisRequestDto.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyAnalysisService.java
  src/main/java/com/investmetic/global/exception/BaseResponse.java
  src/main/java/com/investmetic/global/exception/ErrorCode.java
  src/main/java/com/investmetic/global/exception/GlobalExceptionHandler.java
  src/test/java/com/investmetic/domain/user/controller/UserAdminPageControllerTest.java
  src/test/java/com/investmetic/domain/user/controller/UserMyPageControllerTest.java
Labels: 🐛 fix

#119 Feat/question answer #47
  src/main/java/com/investmetic/domain/notice/model/entity/Notice.java
  src/main/java/com/investmetic/domain/qna/controller/.gitkeep
  src/main/java/com/investmetic/domain/qna/controller/AnswerController.java
  src/main/java/com/investmetic/domain/qna/controller/QuestionController.java
  src/main/java/com/investmetic/domain/qna/dto/SearchCondition.java
  src/main/java/com/investmetic/domain/qna/dto/StateCondition.java
  src/main/java/com/investmetic/domain/qna/dto/request/.gitkeep
  src/main/java/com/investmetic/domain/qna/dto/request/AnswerRequestDto.java
  src/main/java/com/investmetic/domain/qna/dto/request/QuestionRequestDto.java
  src/main/java/com/investmetic/domain/qna/dto/response/.gitkeep
  src/main/java/com/investmetic/domain/qna/dto/response/QuestionsDetailResponse.java
  src/main/java/com/investmetic/domain/qna/dto/response/QuestionsResponse.java
  src/main/java/com/investmetic/domain/qna/model/QnaState.java
  src/main/java/com/investmetic/domain/qna/model/entity/Answer.java
  src/main/java/com/investmetic/domain/qna/model/entity/Question.java
  src/main/java/com/investmetic/domain/qna/repository/.gitkeep
  src/main/java/com/investmetic/domain/qna/repository/AnswerRepository.java
  src/main/java/com/investmetic/domain/qna/repository/QuestionRepository.java
  src/main/java/com/investmetic/domain/qna/service/.gitkeep
  src/main/java/com/investmetic/domain/qna/service/AnswerService.java
  src/main/java/com/investmetic/domain/qna/service/QuestionService.java
  src/main/java/com/investmetic/domain/review/dto/request/ReviewRequestDto.java
  src/main/java/com/investmetic/global/exception/ErrorCode.java
  src/test/java/com/investmetic/domain/qna/repository/QuestionRepositoryTest.java
  src/test/java/com/investmetic/domain/qna/service/QuestionServiceTest.java
Labels: ✨ Feature, 🧪 Test

#169 Fix/닉네임 중복체크 조건 추가 #167
  src/main/java/com/investmetic/domain/user/controller/UserController.java
  src/main/java/com/investmetic/domain/user/dto/response/AvaliableDto.java
  src/main/java/com/investmetic/domain/user/service/UserService.java
  src/test/java/com/investmetic/domain/user/service/UserServiceTest.java
Labels: 🐛 fix

#171 Refactor/s3 strategy folder #160
  src/main/java/com/investmetic/domain/accountverification/controller/AccountVerificationController.java
  src/main/java/com/investmetic/domain/accountverification/service/AccountVerificationService.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyService.java
  src/main/java/com/investmetic/global/util/s3/FilePath.java
  src/main/java/com/investmetic/global/util/s3/S3FileService.java
  src/test/java/com/investmetic/domain/accountverification/service/AccountVerificationServiceTest.java
  src/test/java/com/investmetic/domain/strategy/service/StrategyServiceTest.java
Labels: ♻️ Refactor

#180 Fix/question #179
  src/main/java/com/investmetic/domain/qna/controller/AnswerController.java
  src/main/java/com/investmetic/domain/qna/controller/QuestionController.java
  src/main/java/com/investmetic/domain/qna/dto/request/AnswerRequestDto.java
  src/main/java/com/investmetic/domain/qna/dto/request/QuestionRequestDto.java
  src/main/java/com/investmetic/domain/qna/model/entity/Question.java
  src/main/java/com/investmetic/domain/qna/service/AnswerService.java
  src/main/java/com/investmetic/domain/qna/service/QuestionService.java
  src/test/java/com/investmetic/domain/qna/service/QuestionServiceTest.java
  src/test/java/com/investmetic/domain/strategy/service/AdminStrategyServiceTest.java
  src/test/java/com/investmetic/domain/strategy/service/StockTypeServiceTest.java
  src/test/java/com/investmetic/domain/strategy/service/TradeTypeServiceTest.java
Labels: 🐛 fix

#189 🐛 [fix] 트레이더 문의 목록 조회 내용이 반환 되지 않는 문제 수정
  src/main/java/com/investmetic/domain/qna/service/QuestionService.java
Labels: 🐛 fix

#191 🐛 [fix] 투자자 문의 등록 시에 필요한 DTO 수정
  src/main/java/com/investmetic/domain/qna/dto/request/QuestionRequestDto.java
Labels: 🐛 fix

#197 🐛 [fix] 문의 상세 조회 시 답변자 정보 데이터 조회 추가
  src/main/java/com/investmetic/domain/qna/controller/AnswerController.java
  src/main/java/com/investmetic/domain/qna/dto/request/AnswerRequestDto.java
  src/main/java/com/investmetic/domain/qna/dto/response/AnswerResponseDto.java
  src/main/java/com/investmetic/domain/qna/dto/response/QuestionsResponse.java
  src/main/java/com/investmetic/domain/qna/model/entity/Answer.java
  src/main/java/com/investmetic/domain/qna/service/AnswerService.java
  src/main/java/com/investmetic/domain/qna/service/QuestionService.java
Labels: 🐛 fix

#198 🐛 [fix] 문의 상세 조회 시 답변자 정보 데이터 조회 추가
  src/main/java/com/investmetic/domain/qna/dto/response/QuestionsDetailResponse.java
  src/main/java/com/investmetic/domain/qna/dto/response/QuestionsResponse.java
  src/main/java/com/investmetic/domain/qna/service/QuestionService.java
Labels: 🐛 fix

#186 🐛 [fix] 전략 권한 로직 추가 및 일간 분석 일부 삭제 로직 변경
  src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/investmetic/domain/strategy/model/entity/DailyAnalysis.java
  src/main/java/com/investmetic/domain/strategy/repository/DailyAnalysisRepository.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyAnalysisService.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyService.java
Labels: 🐛 fix

#200 🐛 [fix] 전략 제안서 및 일간분석 삭제 테스트 코드 오류 수정
  src/test/java/com/investmetic/domain/strategy/service/FileDownloadServiceTest.java
  src/test/java/com/investmetic/domain/strategy/service/StrategyDailyAnalysisServiceTest.java
Labels: 🐛 fix

#187 ✨ [feat] 전략통계 계산 기능 구현
  src/main/java/com/investmetic/domain/strategy/dto/response/statistic/AssetManagementDto.java
  src/main/java/com/investmetic/domain/strategy/model/entity/Strategy.java
  src/main/java/com/investmetic/domain/strategy/model/entity/StrategyStatistics.java
  src/main/java/com/investmetic/domain/strategy/repository/DailyAnalysisRepository.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyStatisticsRepository.java
  src/main/java/com/investmetic/global/scheduler/Scheduler.java
  src/main/java/com/investmetic/global/scheduler/StrategyStatisticsScheduler.java
  src/test/java/com/investmetic/domain/strategy/repository/StrategyStatisticsRepositoryTest.java
  src/test/java/com/investmetic/global/scheduler/StrategyStatisticsSchedulerTest.java
Labels: ✨ Feature, ♻️ Refactor, 🧪 Test

#202 🐛 [fix] 답변 대기 중일 경우 null로 인해 조회가 안되는 문제 해결
  src/main/java/com/investmetic/domain/qna/service/QuestionService.java
Labels: 🐛 fix

#205 Fix/qna #203
  src/main/java/com/investmetic/domain/accountverification/controller/AccountVerificationController.java
  src/main/java/com/investmetic/domain/qna/service/QuestionService.java
Labels: 🐛 fix

#165 Feat/비밀번호 재설정 기능 구현 #11
  src/main/java/com/investmetic/domain/user/controller/UserController.java
  src/main/java/com/investmetic/domain/user/service/UserMyPageService.java
  src/main/java/com/investmetic/domain/user/service/UserService.java
  src/main/java/com/investmetic/global/exception/ErrorCode.java
  src/main/java/com/investmetic/global/util/stibee/StibeeEmailService.java
  src/main/java/com/investmetic/global/util/stibee/client/AutoApiStibeeClient.java
  src/test/java/com/investmetic/domain/user/service/UserServiceTest.java
Labels: ✨ Feature

#209 ♻️ [refactor] UserController Swagger 추가 및 수정
  src/main/java/com/investmetic/domain/user/controller/LoginController.java
  src/main/java/com/investmetic/domain/user/controller/LogoutController.java
  src/main/java/com/investmetic/domain/user/controller/ReIssueController.java
  src/main/java/com/investmetic/domain/user/controller/UserController.java
Labels: ♻️ Refactor

#206 [Feat]공지 사항 상세 조회 및 등록 기능
  src/main/java/com/investmetic/domain/notice/controller/.gitkeep
  src/main/java/com/investmetic/domain/notice/controller/NoticeController.java
  src/main/java/com/investmetic/domain/notice/dto/request/.gitkeep
  src/main/java/com/investmetic/domain/notice/dto/request/NoticeRegisterDto.java
  src/main/java/com/investmetic/domain/notice/dto/response/.gitkeep
  src/main/java/com/investmetic/domain/notice/dto/response/NoticeDetailResponseDto.java
  src/main/java/com/investmetic/domain/notice/dto/response/NoticeFileResponseDto.java
  src/main/java/com/investmetic/domain/notice/model/entity/Notice.java
  src/main/java/com/investmetic/domain/notice/model/entity/NoticeFile.java
  src/main/java/com/investmetic/domain/notice/repository/.gitkeep
  src/main/java/com/investmetic/domain/notice/repository/NoticeFileRepository.java
  src/main/java/com/investmetic/domain/notice/repository/NoticeRepository.java
  src/main/java/com/investmetic/domain/notice/repository/NoticeRepositoryCustom.java
  src/main/java/com/investmetic/domain/notice/repository/NoticeRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/notice/service/.gitkeep
  src/main/java/com/investmetic/domain/notice/service/NoticeService.java
  src/main/java/com/investmetic/global/exception/ErrorCode.java
  src/test/java/com/investmetic/domain/notice/service/NoticeServiceTest.java
Labels: ✨ Feature

#210 🐛 [fix] 실계좌 인증 권한 로직 추가
  src/main/java/com/investmetic/domain/accountverification/controller/AccountVerificationController.java
  src/main/java/com/investmetic/domain/accountverification/service/AccountVerificationService.java
  src/main/java/com/investmetic/domain/qna/controller/QuestionController.java
  src/test/java/com/investmetic/domain/accountverification/service/AccountVerificationServiceTest.java
Labels: 🐛 fix

#211 🐛 [fix] QNA 오류 및 상세 조회 시 전략 ID 추가
  src/main/java/com/investmetic/domain/qna/controller/AnswerController.java
  src/main/java/com/investmetic/domain/qna/dto/response/QuestionsDetailResponse.java
  src/main/java/com/investmetic/domain/qna/service/QuestionService.java
Labels: 🐛 fix

#184 Refactor/delete user #12
  src/main/java/com/investmetic/domain/notice/model/entity/Notice.java
  src/main/java/com/investmetic/domain/notice/repository/NoticeRepository.java
  src/main/java/com/investmetic/domain/qna/repository/AnswerRepository.java
  src/main/java/com/investmetic/domain/qna/repository/QuestionRepository.java
  src/main/java/com/investmetic/domain/review/repository/ReviewRepository.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyService.java
  src/main/java/com/investmetic/domain/subscription/repository/SubscriptionRepository.java
  src/main/java/com/investmetic/domain/user/controller/UserAdminController.java
  src/main/java/com/investmetic/domain/user/controller/UserMyPageController.java
  src/main/java/com/investmetic/domain/user/repository/UserRepository.java
  src/main/java/com/investmetic/domain/user/repository/UserRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/user/service/UserAdminService.java
  src/main/java/com/investmetic/domain/user/service/logic/UserCommonLogic.java
  src/test/java/com/investmetic/domain/strategy/service/StrategyServiceTest.java
  src/test/java/com/investmetic/domain/user/controller/UserMyPageControllerTest.java
  src/test/java/com/investmetic/domain/user/repository/AdminPageUserRepositoryTest.java
  src/test/java/com/investmetic/domain/user/service/AdminPageUserServiceTest.java
  src/test/java/com/investmetic/domain/user/service/UserCommonLogicTest.java
Labels: ♻️ Refactor, 🐛 fix

#215 🐛 [fix] 통계계산 누락된값 수정
  src/main/java/com/investmetic/domain/strategy/model/entity/StrategyStatistics.java
  src/main/java/com/investmetic/global/scheduler/StrategyStatisticsScheduler.java
Labels: 🐛 fix

#218 🐛 [fix] 문의 조회(투자자, 트레이더, 관리자) DTO 수정
  src/main/java/com/investmetic/domain/qna/service/QuestionService.java
Labels: 🐛 fix

#220 :sparkles: [feat] : 트레이더 전략 목록 조회 기능
  src/main/java/com/investmetic/domain/strategy/controller/StrategyRankingController.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepositoryCustom.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyListingService.java
Labels: ✨ Feature

#222 🐛 [fix] 통계 응답 수정
  src/main/java/com/investmetic/domain/strategy/dto/response/statistic/AssetManagementDto.java
  src/main/java/com/investmetic/domain/strategy/dto/response/statistic/DdMddInfoDto.java
  src/main/java/com/investmetic/domain/strategy/dto/response/statistic/ProfitLossDto.java
  src/main/java/com/investmetic/domain/strategy/dto/response/statistic/TradingInfoDto.java
  src/main/java/com/investmetic/global/scheduler/DailyAnalysisScheduler.java
  src/main/java/com/investmetic/global/scheduler/StrategyStatisticsScheduler.java
Labels: ♻️ Refactor, 🐛 fix

#224 🐛 [fix] 관리자의 문의 조회시 전략명 반환값 수정
  src/main/java/com/investmetic/domain/qna/dto/QuestionStrategyInfoDto.java
  src/main/java/com/investmetic/domain/qna/dto/response/QuestionsResponse.java
  src/main/java/com/investmetic/domain/qna/service/QuestionService.java
Labels: 🐛 fix

#225 공지사항 목록 조회 기능 #177
  src/main/java/com/investmetic/domain/notice/controller/NoticeController.java
  src/main/java/com/investmetic/domain/notice/dto/object/NoticeOwnerDto.java
  src/main/java/com/investmetic/domain/notice/dto/response/NoticeListDto.java
  src/main/java/com/investmetic/domain/notice/repository/NoticeRepositoryCustom.java
  src/main/java/com/investmetic/domain/notice/repository/NoticeRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/notice/service/NoticeService.java
  src/main/java/com/investmetic/domain/user/controller/UserMyPageController.java
  src/main/java/com/investmetic/domain/user/dto/response/UserProfileDto.java
  src/main/java/com/investmetic/domain/user/repository/UserRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/user/service/UserMyPageService.java
  src/test/java/com/investmetic/domain/notice/service/NoticeListTest.java
Labels: ✨ Feature

#230 ♻️ [refactor] 일간분석, 월간분석 응답 소수점 수정
  src/main/java/com/investmetic/domain/strategy/dto/response/DailyAnalysisResponse.java
  src/main/java/com/investmetic/domain/strategy/dto/response/MonthlyAnalysisResponse.java
Labels: ♻️ Refactor, 🚨Hotfix

#228 ✨[feat] 문의사항 관리자 삭제 기능 추가
  src/main/java/com/investmetic/domain/qna/controller/QuestionController.java
  src/main/java/com/investmetic/domain/qna/service/QuestionService.java
Labels: ✨ Feature

#229 Feat/delete-notice #176
  src/main/java/com/investmetic/domain/notice/controller/NoticeController.java
  src/main/java/com/investmetic/domain/notice/repository/NoticeFileRepository.java
  src/main/java/com/investmetic/domain/notice/service/NoticeService.java
  src/main/java/com/investmetic/domain/user/service/UserMyPageService.java
  src/main/java/com/investmetic/domain/user/service/UserService.java
  src/main/java/com/investmetic/global/util/s3/S3FileService.java
  src/test/java/com/investmetic/domain/notice/service/NoticeDeleteServiceTest.java
  src/test/java/com/investmetic/domain/user/controller/UserMyPageControllerTest.java
Labels: ✨ Feature, ♻️ Refactor, 🧪 Test

#232 Feat/로그인 유지기능 추가 #166
  src/main/java/com/investmetic/domain/user/controller/ReIssueController.java
  src/main/java/com/investmetic/domain/user/dto/request/LoginRequestDto.java
  src/main/java/com/investmetic/domain/user/service/LogoutService.java
  src/main/java/com/investmetic/global/config/RememberMeConfig.java
  src/main/java/com/investmetic/global/config/SecurityConfig.java
  src/main/java/com/investmetic/global/exception/ErrorCode.java
  src/main/java/com/investmetic/global/security/filter/JWTFilter.java
  src/main/java/com/investmetic/global/security/filter/LoginFilter.java
  src/main/java/com/investmetic/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/investmetic/global/security/repository/RedisRememberMeTokenRepository.java
  src/main/java/com/investmetic/global/util/RedisUtil.java
Labels: ✨ Feature

#221 Feat/공지사항수정#195
  src/main/java/com/investmetic/domain/notice/controller/NoticeController.java
  src/main/java/com/investmetic/domain/notice/model/entity/Notice.java
  src/main/java/com/investmetic/domain/notice/model/entity/NoticeFile.java
  src/main/java/com/investmetic/domain/notice/repository/NoticeFileRepository.java
  src/main/java/com/investmetic/domain/notice/service/NoticeService.java
Labels: ✨ Feature
